/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Logica.clsCarton;
import Datos.BingoDatos;
import Logica.clsBolitas;
import Logica.clsPersona;
import java.util.ArrayList;
import javafx.scene.input.KeyCode;
import static javafx.scene.input.KeyCode.O;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Manyor
 */
public class frmBingo extends javax.swing.JFrame {

    private ArrayList<clsPersona> personas = new ArrayList<clsPersona>();
    BingoDatos bingoDatos;
    DefaultTableModel bingoModel;
    clsBolitas bolita;

    /**
     * Creates new form frmBingo
     */
    public frmBingo() {
        initComponents();
        bingoDatos = new BingoDatos();
        bolita = new clsBolitas(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        bingo1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        lblEstado1 = new javax.swing.JLabel();
        btnDatosCliente1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        bingo2 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        lblEstado2 = new javax.swing.JLabel();
        btnDatosCliente2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        bingo3 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        lblEstado3 = new javax.swing.JLabel();
        btnDatosCliente3 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        bingo4 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        lblEstado4 = new javax.swing.JLabel();
        btnDatosCliente4 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        bingo5 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        lblEstado5 = new javax.swing.JLabel();
        btnDatosCliente5 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        bingo6 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        lblEstado6 = new javax.swing.JLabel();
        btnDatosCliente6 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane9 = new javax.swing.JScrollPane();
        bingo7 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        lblEstado7 = new javax.swing.JLabel();
        btnDatosCliente7 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane10 = new javax.swing.JScrollPane();
        bingo8 = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        lblEstado8 = new javax.swing.JLabel();
        btnDatosCliente8 = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane11 = new javax.swing.JScrollPane();
        bingo9 = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        lblEstado9 = new javax.swing.JLabel();
        btnDatosCliente9 = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane12 = new javax.swing.JScrollPane();
        bingo10 = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        lblEstado10 = new javax.swing.JLabel();
        btnDatosCliente10 = new javax.swing.JButton();
        btnGenerarCar = new javax.swing.JButton();
        btnVenderCarton = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBolitas = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TICO BINGO");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cartón 1", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        bingo1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "B", "I", "N", "G", "O"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        bingo1.setCellSelectionEnabled(true);
        bingo1.setGridColor(new java.awt.Color(0, 0, 0));
        bingo1.setPreferredSize(new java.awt.Dimension(100, 100));
        bingo1.getTableHeader().setResizingAllowed(false);
        bingo1.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(bingo1);
        if (bingo1.getColumnModel().getColumnCount() > 0) {
            bingo1.getColumnModel().getColumn(0).setResizable(false);
            bingo1.getColumnModel().getColumn(1).setResizable(false);
            bingo1.getColumnModel().getColumn(2).setResizable(false);
            bingo1.getColumnModel().getColumn(3).setResizable(false);
            bingo1.getColumnModel().getColumn(4).setResizable(false);
        }

        jLabel1.setText("Estado");

        lblEstado1.setForeground(new java.awt.Color(51, 153, 0));
        lblEstado1.setText("DISPONIBLE");

        btnDatosCliente1.setText("Datos del Cliente");
        btnDatosCliente1.setEnabled(false);
        btnDatosCliente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDatosCliente1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(btnDatosCliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(lblEstado1)))
                .addGap(61, 61, 61))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblEstado1))
                .addGap(18, 18, 18)
                .addComponent(btnDatosCliente1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cartón 2", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        bingo2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "B", "I", "N", "G", "O"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        bingo2.setCellSelectionEnabled(true);
        bingo2.setGridColor(new java.awt.Color(0, 0, 0));
        bingo2.setPreferredSize(new java.awt.Dimension(100, 100));
        bingo2.getTableHeader().setResizingAllowed(false);
        bingo2.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(bingo2);
        if (bingo2.getColumnModel().getColumnCount() > 0) {
            bingo2.getColumnModel().getColumn(0).setResizable(false);
            bingo2.getColumnModel().getColumn(1).setResizable(false);
            bingo2.getColumnModel().getColumn(2).setResizable(false);
            bingo2.getColumnModel().getColumn(3).setResizable(false);
            bingo2.getColumnModel().getColumn(4).setResizable(false);
        }

        jLabel2.setText("Estado");

        lblEstado2.setForeground(new java.awt.Color(51, 153, 0));
        lblEstado2.setText("DISPONIBLE");

        btnDatosCliente2.setText("Datos del Cliente");
        btnDatosCliente2.setEnabled(false);
        btnDatosCliente2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDatosCliente2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnDatosCliente2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(lblEstado2)))
                .addGap(61, 61, 61))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblEstado2))
                .addGap(18, 18, 18)
                .addComponent(btnDatosCliente2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cartón 3", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        bingo3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "B", "I", "N", "G", "O"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        bingo3.setCellSelectionEnabled(true);
        bingo3.setGridColor(new java.awt.Color(0, 0, 0));
        bingo3.setPreferredSize(new java.awt.Dimension(100, 100));
        bingo3.getTableHeader().setResizingAllowed(false);
        bingo3.getTableHeader().setReorderingAllowed(false);
        jScrollPane5.setViewportView(bingo3);
        if (bingo3.getColumnModel().getColumnCount() > 0) {
            bingo3.getColumnModel().getColumn(0).setResizable(false);
            bingo3.getColumnModel().getColumn(1).setResizable(false);
            bingo3.getColumnModel().getColumn(2).setResizable(false);
            bingo3.getColumnModel().getColumn(3).setResizable(false);
            bingo3.getColumnModel().getColumn(4).setResizable(false);
        }

        jLabel3.setText("Estado");

        lblEstado3.setForeground(new java.awt.Color(51, 153, 0));
        lblEstado3.setText("DISPONIBLE");

        btnDatosCliente3.setText("Datos del Cliente");
        btnDatosCliente3.setEnabled(false);
        btnDatosCliente3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDatosCliente3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnDatosCliente3, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(lblEstado3)))
                .addGap(61, 61, 61))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblEstado3))
                .addGap(18, 18, 18)
                .addComponent(btnDatosCliente3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cartón 4", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        bingo4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "B", "I", "N", "G", "O"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        bingo4.setCellSelectionEnabled(true);
        bingo4.setGridColor(new java.awt.Color(0, 0, 0));
        bingo4.setPreferredSize(new java.awt.Dimension(100, 100));
        bingo4.getTableHeader().setResizingAllowed(false);
        bingo4.getTableHeader().setReorderingAllowed(false);
        jScrollPane6.setViewportView(bingo4);
        if (bingo4.getColumnModel().getColumnCount() > 0) {
            bingo4.getColumnModel().getColumn(0).setResizable(false);
            bingo4.getColumnModel().getColumn(1).setResizable(false);
            bingo4.getColumnModel().getColumn(2).setResizable(false);
            bingo4.getColumnModel().getColumn(3).setResizable(false);
            bingo4.getColumnModel().getColumn(4).setResizable(false);
        }

        jLabel4.setText("Estado");

        lblEstado4.setForeground(new java.awt.Color(51, 153, 0));
        lblEstado4.setText("DISPONIBLE");

        btnDatosCliente4.setText("Datos del Cliente");
        btnDatosCliente4.setEnabled(false);
        btnDatosCliente4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDatosCliente4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnDatosCliente4, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(lblEstado4)))
                .addGap(61, 61, 61))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblEstado4))
                .addGap(18, 18, 18)
                .addComponent(btnDatosCliente4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cartón 5", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        bingo5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "B", "I", "N", "G", "O"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        bingo5.setCellSelectionEnabled(true);
        bingo5.setGridColor(new java.awt.Color(0, 0, 0));
        bingo5.setPreferredSize(new java.awt.Dimension(100, 100));
        bingo5.getTableHeader().setResizingAllowed(false);
        bingo5.getTableHeader().setReorderingAllowed(false);
        jScrollPane7.setViewportView(bingo5);
        if (bingo5.getColumnModel().getColumnCount() > 0) {
            bingo5.getColumnModel().getColumn(0).setResizable(false);
            bingo5.getColumnModel().getColumn(1).setResizable(false);
            bingo5.getColumnModel().getColumn(2).setResizable(false);
            bingo5.getColumnModel().getColumn(3).setResizable(false);
            bingo5.getColumnModel().getColumn(4).setResizable(false);
        }

        jLabel5.setText("Estado");

        lblEstado5.setForeground(new java.awt.Color(51, 153, 0));
        lblEstado5.setText("DISPONIBLE");

        btnDatosCliente5.setText("Datos del Cliente");
        btnDatosCliente5.setEnabled(false);
        btnDatosCliente5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDatosCliente5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnDatosCliente5, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(lblEstado5)))
                .addGap(61, 61, 61))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblEstado5))
                .addGap(18, 18, 18)
                .addComponent(btnDatosCliente5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cartón 6", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        bingo6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "B", "I", "N", "G", "O"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        bingo6.setCellSelectionEnabled(true);
        bingo6.setGridColor(new java.awt.Color(0, 0, 0));
        bingo6.setPreferredSize(new java.awt.Dimension(100, 100));
        bingo6.getTableHeader().setResizingAllowed(false);
        bingo6.getTableHeader().setReorderingAllowed(false);
        jScrollPane8.setViewportView(bingo6);
        if (bingo6.getColumnModel().getColumnCount() > 0) {
            bingo6.getColumnModel().getColumn(0).setResizable(false);
            bingo6.getColumnModel().getColumn(1).setResizable(false);
            bingo6.getColumnModel().getColumn(2).setResizable(false);
            bingo6.getColumnModel().getColumn(3).setResizable(false);
            bingo6.getColumnModel().getColumn(4).setResizable(false);
        }

        jLabel6.setText("Estado");

        lblEstado6.setForeground(new java.awt.Color(51, 153, 0));
        lblEstado6.setText("DISPONIBLE");

        btnDatosCliente6.setText("Datos del Cliente");
        btnDatosCliente6.setEnabled(false);
        btnDatosCliente6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDatosCliente6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnDatosCliente6, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(lblEstado6)))
                .addGap(61, 61, 61))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblEstado6))
                .addGap(18, 18, 18)
                .addComponent(btnDatosCliente6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cartón 7", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        bingo7.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "B", "I", "N", "G", "O"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        bingo7.setCellSelectionEnabled(true);
        bingo7.setGridColor(new java.awt.Color(0, 0, 0));
        bingo7.setPreferredSize(new java.awt.Dimension(100, 100));
        bingo7.getTableHeader().setResizingAllowed(false);
        bingo7.getTableHeader().setReorderingAllowed(false);
        jScrollPane9.setViewportView(bingo7);
        if (bingo7.getColumnModel().getColumnCount() > 0) {
            bingo7.getColumnModel().getColumn(0).setResizable(false);
            bingo7.getColumnModel().getColumn(1).setResizable(false);
            bingo7.getColumnModel().getColumn(2).setResizable(false);
            bingo7.getColumnModel().getColumn(3).setResizable(false);
            bingo7.getColumnModel().getColumn(4).setResizable(false);
        }

        jLabel7.setText("Estado");

        lblEstado7.setForeground(new java.awt.Color(51, 153, 0));
        lblEstado7.setText("DISPONIBLE");

        btnDatosCliente7.setText("Datos del Cliente");
        btnDatosCliente7.setEnabled(false);
        btnDatosCliente7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDatosCliente7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnDatosCliente7, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(lblEstado7)))
                .addGap(61, 61, 61))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lblEstado7))
                .addGap(18, 18, 18)
                .addComponent(btnDatosCliente7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cartón 8", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        bingo8.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "B", "I", "N", "G", "O"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        bingo8.setCellSelectionEnabled(true);
        bingo8.setGridColor(new java.awt.Color(0, 0, 0));
        bingo8.setPreferredSize(new java.awt.Dimension(100, 100));
        bingo8.getTableHeader().setResizingAllowed(false);
        bingo8.getTableHeader().setReorderingAllowed(false);
        jScrollPane10.setViewportView(bingo8);
        if (bingo8.getColumnModel().getColumnCount() > 0) {
            bingo8.getColumnModel().getColumn(0).setResizable(false);
            bingo8.getColumnModel().getColumn(1).setResizable(false);
            bingo8.getColumnModel().getColumn(2).setResizable(false);
            bingo8.getColumnModel().getColumn(3).setResizable(false);
            bingo8.getColumnModel().getColumn(4).setResizable(false);
        }

        jLabel8.setText("Estado");

        lblEstado8.setForeground(new java.awt.Color(51, 153, 0));
        lblEstado8.setText("DISPONIBLE");

        btnDatosCliente8.setText("Datos del Cliente");
        btnDatosCliente8.setEnabled(false);
        btnDatosCliente8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDatosCliente8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(lblEstado8)))
                .addGap(61, 61, 61))
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnDatosCliente8, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lblEstado8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(btnDatosCliente8))
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cartón 9", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        bingo9.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "B", "I", "N", "G", "O"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        bingo9.setCellSelectionEnabled(true);
        bingo9.setGridColor(new java.awt.Color(0, 0, 0));
        bingo9.setPreferredSize(new java.awt.Dimension(100, 100));
        bingo9.getTableHeader().setResizingAllowed(false);
        bingo9.getTableHeader().setReorderingAllowed(false);
        jScrollPane11.setViewportView(bingo9);
        if (bingo9.getColumnModel().getColumnCount() > 0) {
            bingo9.getColumnModel().getColumn(0).setResizable(false);
            bingo9.getColumnModel().getColumn(1).setResizable(false);
            bingo9.getColumnModel().getColumn(2).setResizable(false);
            bingo9.getColumnModel().getColumn(3).setResizable(false);
            bingo9.getColumnModel().getColumn(4).setResizable(false);
        }

        jLabel9.setText("Estado");

        lblEstado9.setForeground(new java.awt.Color(51, 153, 0));
        lblEstado9.setText("DISPONIBLE");

        btnDatosCliente9.setText("Datos del Cliente");
        btnDatosCliente9.setEnabled(false);
        btnDatosCliente9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDatosCliente9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnDatosCliente9, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(lblEstado9)))
                .addGap(61, 61, 61))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(lblEstado9))
                .addGap(18, 18, 18)
                .addComponent(btnDatosCliente9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cartón 10", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        bingo10.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "B", "I", "N", "G", "O"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        bingo10.setCellSelectionEnabled(true);
        bingo10.setGridColor(new java.awt.Color(0, 0, 0));
        bingo10.setPreferredSize(new java.awt.Dimension(100, 100));
        bingo10.getTableHeader().setResizingAllowed(false);
        bingo10.getTableHeader().setReorderingAllowed(false);
        jScrollPane12.setViewportView(bingo10);
        if (bingo10.getColumnModel().getColumnCount() > 0) {
            bingo10.getColumnModel().getColumn(0).setResizable(false);
            bingo10.getColumnModel().getColumn(1).setResizable(false);
            bingo10.getColumnModel().getColumn(2).setResizable(false);
            bingo10.getColumnModel().getColumn(3).setResizable(false);
            bingo10.getColumnModel().getColumn(4).setResizable(false);
        }

        jLabel10.setText("Estado");

        lblEstado10.setForeground(new java.awt.Color(51, 153, 0));
        lblEstado10.setText("DISPONIBLE");

        btnDatosCliente10.setText("Datos del Cliente");
        btnDatosCliente10.setEnabled(false);
        btnDatosCliente10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDatosCliente10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnDatosCliente10, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(lblEstado10)))
                .addGap(61, 61, 61))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(lblEstado10))
                .addGap(18, 18, 18)
                .addComponent(btnDatosCliente10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnGenerarCar.setText("Generar Cartones");
        btnGenerarCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarCarActionPerformed(evt);
            }
        });

        btnVenderCarton.setText("Vender Cartón");
        btnVenderCarton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVenderCartonActionPerformed(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Tico Bingo logo.jpg"))); // NOI18N

        tblBolitas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "B", "O", "L", "A"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblBolitas);
        if (tblBolitas.getColumnModel().getColumnCount() > 0) {
            tblBolitas.getColumnModel().getColumn(0).setResizable(false);
            tblBolitas.getColumnModel().getColumn(1).setResizable(false);
            tblBolitas.getColumnModel().getColumn(2).setResizable(false);
            tblBolitas.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jMenu1.setText("Archivo");

        jMenuItem5.setText("Salir");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        jMenuItem1.setText("Nuevo Juego");
        jMenu2.add(jMenuItem1);

        jMenuItem2.setText("Generar Cartones");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem3.setText("Vender Cartones");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuItem4.setText("Comenzar Juego");
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(182, 182, 182)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel11)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnGenerarCar)
                                .addGap(18, 18, 18)
                                .addComponent(btnVenderCarton))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnGenerarCar)
                                    .addComponent(btnVenderCarton)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel11)))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerarCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarCarActionPerformed
        // TODO add your handling code here:
        bingo1.setModel(llenarBingos(0, bingo1));
        bingo2.setModel(llenarBingos(1, bingo2));
        bingo3.setModel(llenarBingos(2, bingo3));
        bingo4.setModel(llenarBingos(3, bingo4));
        bingo5.setModel(llenarBingos(4, bingo5));
        bingo6.setModel(llenarBingos(5, bingo6));
        bingo7.setModel(llenarBingos(6, bingo7));
        bingo8.setModel(llenarBingos(7, bingo8));
        bingo9.setModel(llenarBingos(8, bingo9));
        bingo10.setModel(llenarBingos(9, bingo10));
        btnGenerarCar.setEnabled(false);
        bolita.start();
    }//GEN-LAST:event_btnGenerarCarActionPerformed

    private void btnDatosCliente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDatosCliente1ActionPerformed
        mostrarDatosPersona(1);
    }//GEN-LAST:event_btnDatosCliente1ActionPerformed

    private void btnDatosCliente2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDatosCliente2ActionPerformed
        mostrarDatosPersona(2);
    }//GEN-LAST:event_btnDatosCliente2ActionPerformed

    private void btnVenderCartonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVenderCartonActionPerformed
        // TODO add your handling code here:
        frmComprarCarton ventanaComprar = new frmComprarCarton(this, true);
        ventanaComprar.setVistaBingo(this);
        ventanaComprar.setVisible(true);
    }//GEN-LAST:event_btnVenderCartonActionPerformed

    private void btnDatosCliente3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDatosCliente3ActionPerformed
        mostrarDatosPersona(3);
    }//GEN-LAST:event_btnDatosCliente3ActionPerformed

    private void btnDatosCliente4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDatosCliente4ActionPerformed
        mostrarDatosPersona(4);
    }//GEN-LAST:event_btnDatosCliente4ActionPerformed

    private void btnDatosCliente5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDatosCliente5ActionPerformed
        // TODO add your handling code here:
        mostrarDatosPersona(5);
    }//GEN-LAST:event_btnDatosCliente5ActionPerformed

    private void btnDatosCliente6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDatosCliente6ActionPerformed
        // TODO add your handling code here:
        mostrarDatosPersona(6);
    }//GEN-LAST:event_btnDatosCliente6ActionPerformed

    private void btnDatosCliente7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDatosCliente7ActionPerformed
        // TODO add your handling code here:
        mostrarDatosPersona(7);
    }//GEN-LAST:event_btnDatosCliente7ActionPerformed

    private void btnDatosCliente8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDatosCliente8ActionPerformed
        // TODO add your handling code here:
        mostrarDatosPersona(8);
    }//GEN-LAST:event_btnDatosCliente8ActionPerformed

    private void btnDatosCliente9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDatosCliente9ActionPerformed
        // TODO add your handling code here:
        mostrarDatosPersona(9);
    }//GEN-LAST:event_btnDatosCliente9ActionPerformed

    private void btnDatosCliente10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDatosCliente10ActionPerformed
        // TODO add your handling code here:
        mostrarDatosPersona(10);
    }//GEN-LAST:event_btnDatosCliente10ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        frmComprarCarton ventanaComprar = new frmComprarCarton(this, true);
        ventanaComprar.setVistaBingo(this);
        ventanaComprar.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        bingo1.setModel(llenarBingos(0, bingo1));
        bingo2.setModel(llenarBingos(1, bingo2));
        bingo3.setModel(llenarBingos(2, bingo3));
        bingo4.setModel(llenarBingos(3, bingo4));
        bingo5.setModel(llenarBingos(4, bingo5));
        bingo6.setModel(llenarBingos(5, bingo6));
        bingo7.setModel(llenarBingos(6, bingo7));
        bingo8.setModel(llenarBingos(7, bingo8));
        bingo9.setModel(llenarBingos(8, bingo9));
        bingo10.setModel(llenarBingos(9, bingo10));
        btnGenerarCar.setEnabled(false);
        bolita.start();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmBingo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmBingo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmBingo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmBingo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new frmBingo().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable bingo1;
    private javax.swing.JTable bingo10;
    private javax.swing.JTable bingo2;
    private javax.swing.JTable bingo3;
    private javax.swing.JTable bingo4;
    private javax.swing.JTable bingo5;
    private javax.swing.JTable bingo6;
    private javax.swing.JTable bingo7;
    private javax.swing.JTable bingo8;
    private javax.swing.JTable bingo9;
    private javax.swing.JButton btnDatosCliente1;
    private javax.swing.JButton btnDatosCliente10;
    private javax.swing.JButton btnDatosCliente2;
    private javax.swing.JButton btnDatosCliente3;
    private javax.swing.JButton btnDatosCliente4;
    private javax.swing.JButton btnDatosCliente5;
    private javax.swing.JButton btnDatosCliente6;
    private javax.swing.JButton btnDatosCliente7;
    private javax.swing.JButton btnDatosCliente8;
    private javax.swing.JButton btnDatosCliente9;
    private javax.swing.JButton btnGenerarCar;
    private javax.swing.JButton btnVenderCarton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    public javax.swing.JLabel lblEstado1;
    public javax.swing.JLabel lblEstado10;
    public javax.swing.JLabel lblEstado2;
    public javax.swing.JLabel lblEstado3;
    public javax.swing.JLabel lblEstado4;
    public javax.swing.JLabel lblEstado5;
    public javax.swing.JLabel lblEstado6;
    public javax.swing.JLabel lblEstado7;
    public javax.swing.JLabel lblEstado8;
    public javax.swing.JLabel lblEstado9;
    private javax.swing.JTable tblBolitas;
    // End of variables declaration//GEN-END:variables

    private synchronized TableModel llenarBingos(int numBingo, JTable table) {
        bingoModel = (DefaultTableModel) table.getModel();
        int bingo[][] = bingoDatos.getBingo(numBingo);
        Object vectData[] = new Object[5];
        for (int columna = 0; columna < 5; columna++) {
            for (int fila = 0; fila < 5; fila++) {
                vectData[fila] = bingo[fila][columna];
                if (fila == 2 && columna == 2) {
                    vectData[fila] = "**";
                }

            }
            bingoModel.addRow(vectData);
        }
        return bingoModel;
    }

    public void sacarBola(int bolita) {
        Object vectData[] = new Object[1];
        bingoModel = (DefaultTableModel) tblBolitas.getModel();
        vectData[0] = bolita;
        bingoModel.addRow(vectData);
        tblBolitas.setModel(bingoModel);
    }

    public void comprarCarton(clsPersona persona) {
        personas.add(persona);
        String estado = "VENDIDO";
        switch (persona.getNumCarton()) {
            case 1:
                lblEstado1.setText(estado);
                btnDatosCliente1.setEnabled(true);
                break;
            case 2:
                lblEstado2.setText(estado);
                btnDatosCliente2.setEnabled(true);
                break;
            case 3:
                lblEstado3.setText(estado);
                btnDatosCliente3.setEnabled(true);
                break;
            case 4:
                lblEstado4.setText(estado);
                btnDatosCliente4.setEnabled(true);
                break;
            case 5:
                lblEstado5.setText(estado);
                btnDatosCliente5.setEnabled(true);
                break;
            case 6:
                lblEstado6.setText(estado);
                btnDatosCliente6.setEnabled(true);
                break;
            case 7:
                lblEstado7.setText(estado);
                btnDatosCliente7.setEnabled(true);
                break;
            case 8:
                lblEstado8.setText(estado);
                btnDatosCliente8.setEnabled(true);
                break;
            case 9:
                lblEstado9.setText(estado);
                btnDatosCliente9.setEnabled(true);
                break;
            case 10:
                lblEstado10.setText(estado);
                btnDatosCliente10.setEnabled(true);
                break;
        }
    }

    public boolean isCartonDisponible(int numCarton) {
        for (int i = 0; i < personas.size(); i++) {
            clsPersona persona = personas.get(i);

            if (persona.getNumCarton() == numCarton) {
                return false;
            }
        }

        return true;
    }

    private clsPersona buscarPersonaPorNumCarton(int numCarton) {
        for (int i = 0; i < personas.size(); i++) {
            clsPersona persona = personas.get(i);

            if (persona.getNumCarton() == numCarton) {
                return persona;
            }
        }
        return null;
    }
    
    private void mostrarDatosPersona(int numCarton){
        clsPersona persona = buscarPersonaPorNumCarton(numCarton);
        frmDatosCliente ventanaDatos = new frmDatosCliente(this, true);
        ventanaDatos.cargarDatosCliente(persona);
        ventanaDatos.setVisible(true);
    }
}
