/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Logica.clsCarton;
import Datos.BingoDatos;
import Datos.CartonesVendidos;
import Datos.DatosPersona;
import Logica.OperacionArchivo;
import Logica.clsBolitas;
import Logica.clsPersona;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Manyor
 */
public class frmBingo extends javax.swing.JFrame implements ActionListener {

    BingoDatos bingoDatos = new BingoDatos();
    DefaultTableModel bingoModel;
    clsBolitas bolita = new clsBolitas(this);
    CartonesVendidos almacenaCarton = new CartonesVendidos(10);
    Datos.DatosPersona almacenaPersona = new DatosPersona(10);
    clsCarton crtObj;

    JTable tableList[];
    JLabel lableList[];
    JButton jbuttonList[];

    /**
     * Creates new form frmBingo
     */
    public frmBingo() {

        initComponents();
        this.tableList = new JTable[]{bingo1, bingo2, bingo3, bingo4, bingo5, bingo6, bingo7, bingo8, bingo9, bingo10};
        this.lableList = new JLabel[]{lblEstado1, lblEstado2, lblEstado3, lblEstado4, lblEstado5, lblEstado6, lblEstado7, lblEstado8, lblEstado9, lblEstado10};
        this.jbuttonList = new JButton[]{btnDatosCliente1, btnDatosCliente2, btnDatosCliente3, btnDatosCliente4, btnDatosCliente5, btnDatosCliente6, btnDatosCliente7, btnDatosCliente8, btnDatosCliente9, btnDatosCliente10};
        AgregarListener();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        bingo1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        lblEstado1 = new javax.swing.JLabel();
        btnDatosCliente1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        bingo2 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        lblEstado2 = new javax.swing.JLabel();
        btnDatosCliente2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        bingo3 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        lblEstado3 = new javax.swing.JLabel();
        btnDatosCliente3 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        bingo4 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        lblEstado4 = new javax.swing.JLabel();
        btnDatosCliente4 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        bingo5 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        lblEstado5 = new javax.swing.JLabel();
        btnDatosCliente5 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        bingo6 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        lblEstado6 = new javax.swing.JLabel();
        btnDatosCliente6 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane9 = new javax.swing.JScrollPane();
        bingo7 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        lblEstado7 = new javax.swing.JLabel();
        btnDatosCliente7 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane10 = new javax.swing.JScrollPane();
        bingo8 = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        lblEstado8 = new javax.swing.JLabel();
        btnDatosCliente8 = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane11 = new javax.swing.JScrollPane();
        bingo9 = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        lblEstado9 = new javax.swing.JLabel();
        btnDatosCliente9 = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane12 = new javax.swing.JScrollPane();
        bingo10 = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        lblEstado10 = new javax.swing.JLabel();
        btnDatosCliente10 = new javax.swing.JButton();
        btnGenerarCar = new javax.swing.JButton();
        btnVenderCarton = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBolitas = new javax.swing.JTable();
        btnComenzarJuego = new javax.swing.JButton();
        btnGenerarBolita = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TICO BINGO");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cartón 1", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        bingo1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "B", "I", "N", "G", "O"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        bingo1.setCellSelectionEnabled(true);
        bingo1.setGridColor(new java.awt.Color(0, 0, 0));
        bingo1.setPreferredSize(new java.awt.Dimension(100, 100));
        bingo1.getTableHeader().setResizingAllowed(false);
        bingo1.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(bingo1);
        if (bingo1.getColumnModel().getColumnCount() > 0) {
            bingo1.getColumnModel().getColumn(0).setResizable(false);
            bingo1.getColumnModel().getColumn(1).setResizable(false);
            bingo1.getColumnModel().getColumn(2).setResizable(false);
            bingo1.getColumnModel().getColumn(3).setResizable(false);
            bingo1.getColumnModel().getColumn(4).setResizable(false);
        }

        jLabel1.setText("Estado");

        lblEstado1.setForeground(new java.awt.Color(51, 153, 0));
        lblEstado1.setText("DISPONIBLE");

        btnDatosCliente1.setText("Datos del Cliente");
        btnDatosCliente1.setEnabled(false);
        btnDatosCliente1.setName("0"); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(btnDatosCliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(lblEstado1)))
                .addGap(61, 61, 61))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblEstado1))
                .addGap(18, 18, 18)
                .addComponent(btnDatosCliente1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cartón 2", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        bingo2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "B", "I", "N", "G", "O"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        bingo2.setCellSelectionEnabled(true);
        bingo2.setGridColor(new java.awt.Color(0, 0, 0));
        bingo2.setPreferredSize(new java.awt.Dimension(100, 100));
        bingo2.getTableHeader().setResizingAllowed(false);
        bingo2.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(bingo2);
        if (bingo2.getColumnModel().getColumnCount() > 0) {
            bingo2.getColumnModel().getColumn(0).setResizable(false);
            bingo2.getColumnModel().getColumn(1).setResizable(false);
            bingo2.getColumnModel().getColumn(2).setResizable(false);
            bingo2.getColumnModel().getColumn(3).setResizable(false);
            bingo2.getColumnModel().getColumn(4).setResizable(false);
        }

        jLabel2.setText("Estado");

        lblEstado2.setForeground(new java.awt.Color(51, 153, 0));
        lblEstado2.setText("DISPONIBLE");

        btnDatosCliente2.setText("Datos del Cliente");
        btnDatosCliente2.setEnabled(false);
        btnDatosCliente2.setName("1"); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnDatosCliente2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(lblEstado2)))
                .addGap(61, 61, 61))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblEstado2))
                .addGap(18, 18, 18)
                .addComponent(btnDatosCliente2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cartón 3", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        bingo3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "B", "I", "N", "G", "O"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        bingo3.setCellSelectionEnabled(true);
        bingo3.setGridColor(new java.awt.Color(0, 0, 0));
        bingo3.setPreferredSize(new java.awt.Dimension(100, 100));
        bingo3.getTableHeader().setResizingAllowed(false);
        bingo3.getTableHeader().setReorderingAllowed(false);
        jScrollPane5.setViewportView(bingo3);
        if (bingo3.getColumnModel().getColumnCount() > 0) {
            bingo3.getColumnModel().getColumn(0).setResizable(false);
            bingo3.getColumnModel().getColumn(1).setResizable(false);
            bingo3.getColumnModel().getColumn(2).setResizable(false);
            bingo3.getColumnModel().getColumn(3).setResizable(false);
            bingo3.getColumnModel().getColumn(4).setResizable(false);
        }

        jLabel3.setText("Estado");

        lblEstado3.setForeground(new java.awt.Color(51, 153, 0));
        lblEstado3.setText("DISPONIBLE");

        btnDatosCliente3.setText("Datos del Cliente");
        btnDatosCliente3.setEnabled(false);
        btnDatosCliente3.setName("2"); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnDatosCliente3, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(lblEstado3)))
                .addGap(61, 61, 61))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblEstado3))
                .addGap(18, 18, 18)
                .addComponent(btnDatosCliente3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cartón 4", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        bingo4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "B", "I", "N", "G", "O"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        bingo4.setCellSelectionEnabled(true);
        bingo4.setGridColor(new java.awt.Color(0, 0, 0));
        bingo4.setPreferredSize(new java.awt.Dimension(100, 100));
        bingo4.getTableHeader().setResizingAllowed(false);
        bingo4.getTableHeader().setReorderingAllowed(false);
        jScrollPane6.setViewportView(bingo4);
        if (bingo4.getColumnModel().getColumnCount() > 0) {
            bingo4.getColumnModel().getColumn(0).setResizable(false);
            bingo4.getColumnModel().getColumn(1).setResizable(false);
            bingo4.getColumnModel().getColumn(2).setResizable(false);
            bingo4.getColumnModel().getColumn(3).setResizable(false);
            bingo4.getColumnModel().getColumn(4).setResizable(false);
        }

        jLabel4.setText("Estado");

        lblEstado4.setForeground(new java.awt.Color(51, 153, 0));
        lblEstado4.setText("DISPONIBLE");

        btnDatosCliente4.setText("Datos del Cliente");
        btnDatosCliente4.setEnabled(false);
        btnDatosCliente4.setName("3"); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnDatosCliente4, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(lblEstado4)))
                .addGap(61, 61, 61))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblEstado4))
                .addGap(18, 18, 18)
                .addComponent(btnDatosCliente4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cartón 5", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        bingo5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "B", "I", "N", "G", "O"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        bingo5.setCellSelectionEnabled(true);
        bingo5.setGridColor(new java.awt.Color(0, 0, 0));
        bingo5.setPreferredSize(new java.awt.Dimension(100, 100));
        bingo5.getTableHeader().setResizingAllowed(false);
        bingo5.getTableHeader().setReorderingAllowed(false);
        jScrollPane7.setViewportView(bingo5);
        if (bingo5.getColumnModel().getColumnCount() > 0) {
            bingo5.getColumnModel().getColumn(0).setResizable(false);
            bingo5.getColumnModel().getColumn(1).setResizable(false);
            bingo5.getColumnModel().getColumn(2).setResizable(false);
            bingo5.getColumnModel().getColumn(3).setResizable(false);
            bingo5.getColumnModel().getColumn(4).setResizable(false);
        }

        jLabel5.setText("Estado");

        lblEstado5.setForeground(new java.awt.Color(51, 153, 0));
        lblEstado5.setText("DISPONIBLE");

        btnDatosCliente5.setText("Datos del Cliente");
        btnDatosCliente5.setEnabled(false);
        btnDatosCliente5.setName("4"); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnDatosCliente5, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(lblEstado5)))
                .addGap(61, 61, 61))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblEstado5))
                .addGap(18, 18, 18)
                .addComponent(btnDatosCliente5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cartón 6", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        bingo6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "B", "I", "N", "G", "O"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        bingo6.setCellSelectionEnabled(true);
        bingo6.setGridColor(new java.awt.Color(0, 0, 0));
        bingo6.setPreferredSize(new java.awt.Dimension(100, 100));
        bingo6.getTableHeader().setResizingAllowed(false);
        bingo6.getTableHeader().setReorderingAllowed(false);
        jScrollPane8.setViewportView(bingo6);
        if (bingo6.getColumnModel().getColumnCount() > 0) {
            bingo6.getColumnModel().getColumn(0).setResizable(false);
            bingo6.getColumnModel().getColumn(1).setResizable(false);
            bingo6.getColumnModel().getColumn(2).setResizable(false);
            bingo6.getColumnModel().getColumn(3).setResizable(false);
            bingo6.getColumnModel().getColumn(4).setResizable(false);
        }

        jLabel6.setText("Estado");

        lblEstado6.setForeground(new java.awt.Color(51, 153, 0));
        lblEstado6.setText("DISPONIBLE");

        btnDatosCliente6.setText("Datos del Cliente");
        btnDatosCliente6.setEnabled(false);
        btnDatosCliente6.setName("5"); // NOI18N

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnDatosCliente6, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(lblEstado6)))
                .addGap(61, 61, 61))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblEstado6))
                .addGap(18, 18, 18)
                .addComponent(btnDatosCliente6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cartón 7", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        bingo7.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "B", "I", "N", "G", "O"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        bingo7.setCellSelectionEnabled(true);
        bingo7.setGridColor(new java.awt.Color(0, 0, 0));
        bingo7.setPreferredSize(new java.awt.Dimension(100, 100));
        bingo7.getTableHeader().setResizingAllowed(false);
        bingo7.getTableHeader().setReorderingAllowed(false);
        jScrollPane9.setViewportView(bingo7);
        if (bingo7.getColumnModel().getColumnCount() > 0) {
            bingo7.getColumnModel().getColumn(0).setResizable(false);
            bingo7.getColumnModel().getColumn(1).setResizable(false);
            bingo7.getColumnModel().getColumn(2).setResizable(false);
            bingo7.getColumnModel().getColumn(3).setResizable(false);
            bingo7.getColumnModel().getColumn(4).setResizable(false);
        }

        jLabel7.setText("Estado");

        lblEstado7.setForeground(new java.awt.Color(51, 153, 0));
        lblEstado7.setText("DISPONIBLE");

        btnDatosCliente7.setText("Datos del Cliente");
        btnDatosCliente7.setEnabled(false);
        btnDatosCliente7.setName("6"); // NOI18N

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnDatosCliente7, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(lblEstado7)))
                .addGap(61, 61, 61))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lblEstado7))
                .addGap(18, 18, 18)
                .addComponent(btnDatosCliente7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cartón 8", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        bingo8.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "B", "I", "N", "G", "O"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        bingo8.setCellSelectionEnabled(true);
        bingo8.setGridColor(new java.awt.Color(0, 0, 0));
        bingo8.setPreferredSize(new java.awt.Dimension(100, 100));
        bingo8.getTableHeader().setResizingAllowed(false);
        bingo8.getTableHeader().setReorderingAllowed(false);
        jScrollPane10.setViewportView(bingo8);
        if (bingo8.getColumnModel().getColumnCount() > 0) {
            bingo8.getColumnModel().getColumn(0).setResizable(false);
            bingo8.getColumnModel().getColumn(1).setResizable(false);
            bingo8.getColumnModel().getColumn(2).setResizable(false);
            bingo8.getColumnModel().getColumn(3).setResizable(false);
            bingo8.getColumnModel().getColumn(4).setResizable(false);
        }

        jLabel8.setText("Estado");

        lblEstado8.setForeground(new java.awt.Color(51, 153, 0));
        lblEstado8.setText("DISPONIBLE");

        btnDatosCliente8.setText("Datos del Cliente");
        btnDatosCliente8.setEnabled(false);
        btnDatosCliente8.setName("7"); // NOI18N

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(lblEstado8)))
                .addGap(61, 61, 61))
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnDatosCliente8, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lblEstado8))
                .addGap(18, 30, Short.MAX_VALUE)
                .addComponent(btnDatosCliente8))
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cartón 9", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        bingo9.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "B", "I", "N", "G", "O"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        bingo9.setCellSelectionEnabled(true);
        bingo9.setGridColor(new java.awt.Color(0, 0, 0));
        bingo9.setPreferredSize(new java.awt.Dimension(100, 100));
        bingo9.getTableHeader().setResizingAllowed(false);
        bingo9.getTableHeader().setReorderingAllowed(false);
        jScrollPane11.setViewportView(bingo9);
        if (bingo9.getColumnModel().getColumnCount() > 0) {
            bingo9.getColumnModel().getColumn(0).setResizable(false);
            bingo9.getColumnModel().getColumn(1).setResizable(false);
            bingo9.getColumnModel().getColumn(2).setResizable(false);
            bingo9.getColumnModel().getColumn(3).setResizable(false);
            bingo9.getColumnModel().getColumn(4).setResizable(false);
        }

        jLabel9.setText("Estado");

        lblEstado9.setForeground(new java.awt.Color(51, 153, 0));
        lblEstado9.setText("DISPONIBLE");

        btnDatosCliente9.setText("Datos del Cliente");
        btnDatosCliente9.setEnabled(false);
        btnDatosCliente9.setName("8"); // NOI18N

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnDatosCliente9, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(lblEstado9)))
                .addGap(61, 61, 61))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(lblEstado9))
                .addGap(18, 18, 18)
                .addComponent(btnDatosCliente9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cartón 10", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        bingo10.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "B", "I", "N", "G", "O"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        bingo10.setCellSelectionEnabled(true);
        bingo10.setGridColor(new java.awt.Color(0, 0, 0));
        bingo10.setPreferredSize(new java.awt.Dimension(100, 100));
        bingo10.getTableHeader().setResizingAllowed(false);
        bingo10.getTableHeader().setReorderingAllowed(false);
        jScrollPane12.setViewportView(bingo10);
        if (bingo10.getColumnModel().getColumnCount() > 0) {
            bingo10.getColumnModel().getColumn(0).setResizable(false);
            bingo10.getColumnModel().getColumn(1).setResizable(false);
            bingo10.getColumnModel().getColumn(2).setResizable(false);
            bingo10.getColumnModel().getColumn(3).setResizable(false);
            bingo10.getColumnModel().getColumn(4).setResizable(false);
        }

        jLabel10.setText("Estado");

        lblEstado10.setForeground(new java.awt.Color(51, 153, 0));
        lblEstado10.setText("DISPONIBLE");

        btnDatosCliente10.setText("Datos del Cliente");
        btnDatosCliente10.setEnabled(false);
        btnDatosCliente10.setName("9"); // NOI18N

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnDatosCliente10, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(lblEstado10)))
                .addGap(61, 61, 61))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(lblEstado10))
                .addGap(18, 18, 18)
                .addComponent(btnDatosCliente10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnGenerarCar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/bingo.png"))); // NOI18N
        btnGenerarCar.setText("Generar Cartones");
        btnGenerarCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarCarActionPerformed(evt);
            }
        });

        btnVenderCarton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/VenderCarton.png"))); // NOI18N
        btnVenderCarton.setText("Vender Cartón");
        btnVenderCarton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVenderCartonActionPerformed(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Tico Bingo logo.jpg"))); // NOI18N

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 255), 1, true));

        tblBolitas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "B", "O", "L", "A"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblBolitas.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentMoved(java.awt.event.ComponentEvent evt) {
                tblBolitasComponentMoved(evt);
            }
        });
        tblBolitas.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tblBolitasPropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(tblBolitas);
        if (tblBolitas.getColumnModel().getColumnCount() > 0) {
            tblBolitas.getColumnModel().getColumn(0).setResizable(false);
            tblBolitas.getColumnModel().getColumn(1).setResizable(false);
            tblBolitas.getColumnModel().getColumn(2).setResizable(false);
            tblBolitas.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnComenzarJuego.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Comenzar.png"))); // NOI18N
        btnComenzarJuego.setText("Comenzar Juego");
        btnComenzarJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComenzarJuegoActionPerformed(evt);
            }
        });

        btnGenerarBolita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/GenerarBolita.png"))); // NOI18N
        btnGenerarBolita.setText("Generar Bolita");
        btnGenerarBolita.setEnabled(false);
        btnGenerarBolita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarBolitaActionPerformed(evt);
            }
        });

        jMenu1.setText("Archivo");

        jMenuItem5.setText("Salir");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        jMenuItem1.setText("Nuevo Juego");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem2.setText("Generar Cartones");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem3.setText("Vender Cartones");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuItem4.setText("Comenzar Juego");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(182, 182, 182)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel11)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnGenerarCar, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnVenderCarton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnComenzarJuego))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnGenerarBolita, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(223, 223, 223))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnGenerarCar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnVenderCarton)
                                    .addComponent(btnComenzarJuego)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel11)))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(btnGenerarBolita, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerarCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarCarActionPerformed
        // TODO add your handling code here:
        for (int i = 0; i < tableList.length; i++) {
            tableList[i].setModel(llenarBingos(i, tableList[i], 1));
        }
        btnGenerarCar.setEnabled(false);

    }//GEN-LAST:event_btnGenerarCarActionPerformed

    private void btnVenderCartonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVenderCartonActionPerformed
        // TODO add your handling code here:
        frmComprarCarton ventanaComprar = new frmComprarCarton(this, true, this.almacenaCarton, this.almacenaPersona);
        ventanaComprar.setVisible(true);

        almacenaCarton = ventanaComprar.almacenaCarton;
        almacenaPersona = ventanaComprar.dataPersona;
        actualizarLabels();
    }//GEN-LAST:event_btnVenderCartonActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        frmComprarCarton ventanaComprar = new frmComprarCarton(this, true);
        ventanaComprar.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void btnComenzarJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComenzarJuegoActionPerformed
        btnGenerarBolita.setEnabled(true);
    }//GEN-LAST:event_btnComenzarJuegoActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        btnGenerarBolita.setEnabled(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void btnGenerarBolitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarBolitaActionPerformed
        // TODO add your handling code here:
        bolita.start();
    }//GEN-LAST:event_btnGenerarBolitaActionPerformed

    private void tblBolitasComponentMoved(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_tblBolitasComponentMoved
        // TODO add your handling code here:
        checkBingo(bingo1);
    }//GEN-LAST:event_tblBolitasComponentMoved

    private void tblBolitasPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tblBolitasPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_tblBolitasPropertyChange

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmBingo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmBingo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmBingo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmBingo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new frmBingo().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable bingo1;
    private javax.swing.JTable bingo10;
    private javax.swing.JTable bingo2;
    private javax.swing.JTable bingo3;
    private javax.swing.JTable bingo4;
    private javax.swing.JTable bingo5;
    private javax.swing.JTable bingo6;
    private javax.swing.JTable bingo7;
    private javax.swing.JTable bingo8;
    private javax.swing.JTable bingo9;
    private javax.swing.JButton btnComenzarJuego;
    private javax.swing.JButton btnDatosCliente1;
    private javax.swing.JButton btnDatosCliente10;
    private javax.swing.JButton btnDatosCliente2;
    private javax.swing.JButton btnDatosCliente3;
    private javax.swing.JButton btnDatosCliente4;
    private javax.swing.JButton btnDatosCliente5;
    private javax.swing.JButton btnDatosCliente6;
    private javax.swing.JButton btnDatosCliente7;
    private javax.swing.JButton btnDatosCliente8;
    private javax.swing.JButton btnDatosCliente9;
    private javax.swing.JButton btnGenerarBolita;
    private javax.swing.JButton btnGenerarCar;
    private javax.swing.JButton btnVenderCarton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    public javax.swing.JLabel lblEstado1;
    public javax.swing.JLabel lblEstado10;
    public javax.swing.JLabel lblEstado2;
    public javax.swing.JLabel lblEstado3;
    public javax.swing.JLabel lblEstado4;
    public javax.swing.JLabel lblEstado5;
    public javax.swing.JLabel lblEstado6;
    public javax.swing.JLabel lblEstado7;
    public javax.swing.JLabel lblEstado8;
    public javax.swing.JLabel lblEstado9;
    private javax.swing.JTable tblBolitas;
    // End of variables declaration//GEN-END:variables

    private synchronized TableModel llenarBingos(int numBingo, JTable table, int func) {
        bingoModel = (DefaultTableModel) table.getModel();
        bingoModel.setRowCount(0);
        int bingo[][] = bingoDatos.getBingo(numBingo);
        Object vectData[] = new Object[5];
        for (int columna = 0; columna < 5; columna++) {
            for (int fila = 0; fila < 5; fila++) {
                vectData[fila] = bingo[fila][columna];
                if (fila == 2 && columna == 2) {
                    vectData[fila] = "▓";
                }
            }
            bingoModel.addRow(vectData);
        }
        if (func == 1) {
            insertarCartonBingo(numBingo, bingo, null);
        }

        return bingoModel;
    }

    public synchronized boolean sacarBola(int bolita) {
        Object vectData[] = new Object[1];
        bingoModel = (DefaultTableModel) tblBolitas.getModel();
        vectData[0] = bolita;
        bingoModel.addRow(vectData);
        tblBolitas.setModel(bingoModel);
        for (int i = 0; i < 10; i++) {
            checkBingo(tableList[i]);
//validarFila(j, tableList[i]) || validarColumna(j, tableList[i]) || validarDiagonales(j, tableList[i])
            for (int j = 0; j < 5; j++) {
                if (validarFila(j, tableList[i]) || validarColumna(j, tableList[i]) || validarDiagonales(j, tableList[i]) || (validarEsquinas(tableList[i]))) {
                    tableList[i].setBackground(Color.GREEN);
                    JOptionPane.showMessageDialog(this, "Cartón GANADOR " + (i + 1));
                    if (almacenaCarton.getRegistro(i).isEstado()) {
                        guardarRegistroGanador(almacenaCarton.getRegistro(i));
                    }
                    return true;
                }

            }
        }

        return false;
    }

    private void insertarCartonBingo(int numBingo, int[][] bingo, clsPersona persona) {
        crtObj = new clsCarton(numBingo, bingo, false, null);

        if (almacenaCarton.insertCarton(crtObj)) {

        }

    }

    private void actualizarLabels() {
        for (int i = 0; i < lableList.length; i++) {
            if (almacenaCarton.getRegistro(i).isEstado()) {
                lableList[i].setText("VENDIDO");
                tableList[i].setEnabled(true);
                jbuttonList[i].setEnabled(true);
            }
        }
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        JButton button = (JButton) e.getSource();
        clsCarton obj = almacenaCarton.getRegistro(Integer.parseInt(button.getName()));
        frmDatosCliente datosCliente = new frmDatosCliente(this, true, obj);
        datosCliente.setVisible(true);
    }

    private void AgregarListener() {
        for (JButton jbuttonList1 : jbuttonList) {
            jbuttonList1.addActionListener(this);
        }
    }

    private void checkBingo(JTable table) {
        for (int i = 0; i < 5; i++) {
            for (int j = 0; j < 5; j++) {
                if (table.getValueAt(i, j) == tblBolitas.getValueAt(tblBolitas.getRowCount() - 1, 0)) {
                    table.getModel().setValueAt("▓", i, j);
                }
            }

        }

    }

    private boolean validarFila(int fila, JTable table) {
        for (int fil = 0; fil < 5; fil++) {
            int[] filas = new int[5];
            for (int col = 0; col < 5; col++) {
                if (table.getValueAt(fila, col).equals("▓")) {
                    filas[fila] = filas[fila] + 1;
                }
            }
            for (int i = 0; i < filas.length; i++) {
                if (filas[i] == 5) {
                    return true;

                }
            }
        }
        return false;

    }

    private boolean validarColumna(int columna, JTable table) {
        for (int col = 0; col < 5; col++) {
            int[] columnas = new int[5];
            for (int fil = 0; fil < 5; fil++) {
                if (table.getValueAt(fil, col).equals("▓")) {
                    columnas[col] = columnas[col] + 1;
                }
            }
            for (int i = 0; i < columnas.length; i++) {
                if (columnas[i] == 5) {
                    return true;

                }
            }
        }
        return false;

    }

    private boolean validarDiagonales(int columna, JTable table) {
        int diagonal1 = 0;
        int diagonal2 = 0;
        for (int i = 0; i < 5; i++) {
            for (int j = 0; j < 5; j++) {
                if (i == j && table.getValueAt(i, j).equals("▓")) {
                    diagonal1 = diagonal1 + 1;
                }

                if (i + j == 25 - 1 && table.getValueAt(i, j).equals("▓")) {
                    diagonal2 = diagonal2 + 1;

                }
            }
        }
        if (diagonal1 == 5 || diagonal2 == 5) {
            return true;
        }
        return false;

    }

    private boolean validarEsquinas(JTable table) {
        int esquina = 0;
        if (table.getValueAt(0, 0).equals("▓")) {
            esquina = esquina + 1;
        }
        if (table.getValueAt(0, 4).equals("▓")) {
            esquina = esquina + 1;
        }
        if (table.getValueAt(4, 0).equals("▓")) {
            esquina = esquina + 1;
        }
        if (table.getValueAt(4, 4).equals("▓")) {
            esquina = esquina + 1;
        }
        if (esquina == 4) {
            return true;
        }
        return false;

    }

    private void guardarRegistroGanador(clsCarton registro) {
        OperacionArchivo.crearArchivo(registro);
        
    }
}
